import { NextResponse } from "next/server";
import { z } from "zod";
import { closePictureCaptioning, getHostPictureCaptionCompletion, getHostPictureCaptionSubmissions, removePictureCaptionSubmission } from "@/lib/host/rounds";
import { getHost } from "@/lib/host/session";
import { publishLobbyInvalidation } from "@/lib/realtime/lobby-invalidation";

const command = z.object({ commandId: z.string().uuid(), expectedRevision: z.number().int().nonnegative() }).strict();
const schema = z.discriminatedUnion("action", [command.extend({ action: z.literal("remove"), submissionId: z.string().uuid() }).strict(), command.extend({ action: z.literal("close"), confirmMissing: z.boolean() }).strict()]);
export async function GET(_request: Request, context: { params: Promise<{ partyId: string }> }) { const host = await getHost(); if (!host) return NextResponse.json({ error: "not_found" }, { status: 404 }); const { partyId } = await context.params; try { const [submissions, completion] = await Promise.all([getHostPictureCaptionSubmissions(host.id, partyId), getHostPictureCaptionCompletion(host.id, partyId)]); return NextResponse.json({ submissions, completion }); } catch { return NextResponse.json({ error: "not_found" }, { status: 404 }); } }
export async function POST(request: Request, context: { params: Promise<{ partyId: string }> }) { const host = await getHost(); if (!host) return NextResponse.json({ error: "not_found" }, { status: 404 }); const parsed = schema.safeParse(await request.json()); if (!parsed.success) return NextResponse.json({ error: "invalid_request" }, { status: 400 }); const { partyId } = await context.params; try { const result = parsed.data.action === "remove" ? await removePictureCaptionSubmission({ hostId: host.id, partyId, submissionId: parsed.data.submissionId, commandId: parsed.data.commandId, expectedRevision: parsed.data.expectedRevision }) : await closePictureCaptioning({ hostId: host.id, partyId, commandId: parsed.data.commandId, expectedRevision: parsed.data.expectedRevision, confirmMissing: parsed.data.confirmMissing }); await publishLobbyInvalidation({ gameSessionId: result.game_session_id, revision: result.session_revision }); return NextResponse.json({ updated: true }); } catch (error) { const message = error instanceof Error ? error.message : "unavailable"; return NextResponse.json({ error: ["stale_revision", "close_confirmation_required"].includes(message) ? message : "unavailable" }, { status: message === "close_confirmation_required" ? 400 : message === "stale_revision" ? 409 : 503 }); } }