#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6
REPOSITORY="StephanCo32/Quizmaster"
VERCEL_CLI="vercel@59.4.0"

set_environment_secret() {
  local name="$1" value="$2"
  if printf '%s' "$value" | gh secret set "$name" --env production --repo "$REPOSITORY" >/dev/null; then
    WRITTEN_SECRET+=("$name")
    printf '  %s✓ set%s production secret %s\n' "$GREEN" "$RESET" "$name"
  else
    SKIPPED+=("GitHub production secret $name")
    warn "could not set production secret $name"
  fi
}

set_vercel_environment() {
  local name="$1" value="$2" visibility="$3"
  local visibility_flags=()
  case "$visibility" in
    public) visibility_flags=(--visibility config --no-sensitive) ;;
    secret) visibility_flags=(--sensitive) ;;
    *) warn "unknown Vercel visibility for $name"; return 1 ;;
  esac
  printf '%s' "$value" | npx --yes "$VERCEL_CLI" env add "$name" production \
    --force "${visibility_flags[@]}" --token="$VERCEL_TOKEN" >/dev/null
  printf '  %s✓ set%s Vercel Production value %s\n' "$GREEN" "$RESET" "$name"
}

banner "Quizmaster Production setup"

stage "Prerequisites"
say "We'll verify the local tools and GitHub access used by the release pipeline."
for command_name in git node npm npx gh; do
  command -v "$command_name" >/dev/null 2>&1 || {
    warn "$command_name is required but was not found on PATH"
    exit 1
  }
done
gh auth status >/dev/null 2>&1 || {
  warn "GitHub CLI is not authenticated. Run: gh auth login"
  exit 1
}
[[ -z "$(git status --porcelain)" ]] || warn "Local changes are present; setup can continue, but release will require a clean main branch."
if ! command -v gpg >/dev/null 2>&1 || [[ -z "$(gpg --list-secret-keys --with-colons 2>/dev/null | grep '^sec:' || true)" ]]; then
  warn "No GPG signing key was found. Configure one before the release stage."
fi
say "GitHub access and repository state are ready."
pause "Continue to Supabase?"

stage "Supabase Production"
say "Create one hosted Production project. Local development continues to use Supabase CLI."
open_url "https://supabase.com/dashboard/new"
step "Create or select Quizmaster and choose Central EU (Frankfurt)."
step "Keep the generated database password safe; it is required by release migrations."
step "Copy the project reference from https://supabase.com/dashboard/project/<project-ref>."
ask SUPABASE_PROJECT_ID "Project reference:"
open_url "https://supabase.com/dashboard/project/${SUPABASE_PROJECT_ID}/settings/api-keys"
step "Under Settings > API Keys, copy the Project URL and Publishable key."
ask NEXT_PUBLIC_SUPABASE_URL "Project URL:"
ask NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY "Publishable key:"
step "Copy a Secret key. It stays server-only despite the compatibility variable name below."
ask_secret SUPABASE_SERVICE_ROLE_KEY "Secret key:"
ask_secret SUPABASE_DB_PASSWORD "Database password:"
open_url "https://supabase.com/dashboard/account/tokens"
step "Generate a personal access token for GitHub Actions, then copy it."
ask_secret SUPABASE_ACCESS_TOKEN "Supabase access token:"

stage "Vercel Production"
say "Create a Vercel project without Git-triggered preview deployments and link this repository."
open_url "https://vercel.com/account/settings/tokens"
step "Create a token named Quizmaster GitHub Actions and copy it."
ask_secret VERCEL_TOKEN "Vercel token:"
ask VERCEL_PROJECT_NAME "Vercel project name (recommended: quizmaster):"
step "Use your personal username or team slug as the Vercel scope."
ask VERCEL_SCOPE "Vercel scope:"
if ! npx --yes "$VERCEL_CLI" project inspect "$VERCEL_PROJECT_NAME" \
  --scope="$VERCEL_SCOPE" --token="$VERCEL_TOKEN" >/dev/null 2>&1; then
  npx --yes "$VERCEL_CLI" project add "$VERCEL_PROJECT_NAME" \
    --scope="$VERCEL_SCOPE" --token="$VERCEL_TOKEN"
fi
npx --yes "$VERCEL_CLI" link --yes --project "$VERCEL_PROJECT_NAME" \
  --scope="$VERCEL_SCOPE" --token="$VERCEL_TOKEN"
VERCEL_PROJECT_ID=$(node -p "require('./.vercel/project.json').projectId")
VERCEL_ORG_ID=$(node -p "require('./.vercel/project.json').orgId")
set_vercel_environment NEXT_PUBLIC_SUPABASE_URL "$NEXT_PUBLIC_SUPABASE_URL" public
set_vercel_environment NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY "$NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY" public
set_vercel_environment SUPABASE_SERVICE_ROLE_KEY "$SUPABASE_SERVICE_ROLE_KEY" secret

stage "GitHub Production environment"
say "Create the protected secret boundary consumed by the Production release workflow."
gh api --method PUT "repos/${REPOSITORY}/environments/production" --input - \
  <<< '{}' >/dev/null
set_environment_secret NEXT_PUBLIC_SUPABASE_URL "$NEXT_PUBLIC_SUPABASE_URL"
set_environment_secret NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY "$NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY"
set_environment_secret SUPABASE_SERVICE_ROLE_KEY "$SUPABASE_SERVICE_ROLE_KEY"
set_environment_secret SUPABASE_ACCESS_TOKEN "$SUPABASE_ACCESS_TOKEN"
set_environment_secret SUPABASE_DB_PASSWORD "$SUPABASE_DB_PASSWORD"
set_environment_secret SUPABASE_PROJECT_ID "$SUPABASE_PROJECT_ID"
set_environment_secret VERCEL_TOKEN "$VERCEL_TOKEN"
set_environment_secret VERCEL_ORG_ID "$VERCEL_ORG_ID"
set_environment_secret VERCEL_PROJECT_ID "$VERCEL_PROJECT_ID"

stage "First signed release"
say "The tag starts migration and deployment. Continue only after the latest main CI run succeeds."
[[ "$(git branch --show-current 2>/dev/null || git rev-parse --abbrev-ref HEAD)" == "main" ]] || {
  warn "Release must run from the main branch."
  exit 1
}
[[ -z "$(git status --porcelain)" ]] || {
  warn "Commit or stash local changes before releasing Production."
  exit 1
}
LATEST_CI=$(gh run list --repo "$REPOSITORY" --workflow CI --branch main --limit 1 \
  --json conclusion --jq '.[0].conclusion')
[[ "$LATEST_CI" == "success" ]] || {
  warn "Latest main CI conclusion is '$LATEST_CI', not success. Re-run later."
  exit 1
}
ask RELEASE_TAG "Release tag (recommended: v0.1.0):"
[[ "$RELEASE_TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]] || {
  warn "Release tag must use vX.Y.Z."
  exit 1
}
git rev-parse "$RELEASE_TAG" >/dev/null 2>&1 && {
  warn "$RELEASE_TAG already exists; choose a new version."
  exit 1
}
confirm "Create and push signed tag $RELEASE_TAG? This starts Production deployment." || exit 0
git pull --ff-only origin main
git tag -s "$RELEASE_TAG" -m "Release $RELEASE_TAG"
git push origin "$RELEASE_TAG"
open_url "https://github.com/${REPOSITORY}/actions/workflows/release.yml"
pause "Wait for Production release to succeed, then continue."

stage "External uptime monitoring"
say "Create an independent monitor for the public health endpoint."
open_url "https://dashboard.uptimerobot.com/monitors/new"
step "Choose HTTP(s) monitoring and a five-minute interval."
step "Use the Vercel Production URL followed by /api/health."
step "Treat only HTTP 200 as healthy and attach your preferred alert contact."
ask PRODUCTION_URL "Production URL (for the final summary):"
note "Health endpoint: ${PRODUCTION_URL%/}/api/health"
pause "Confirm the monitor is active."

finish