create function public.player_picture_caption_candidates_projection(p_player_id uuid,p_party_code text) returns table(candidate_id uuid,caption text,display_position integer,is_own boolean,own_color text,has_voted boolean,game_session_id uuid,session_revision bigint) language sql stable security definer set search_path='' as $$
 select candidate.id,candidate.caption,candidate.display_position,exists(select 1 from public.picture_caption_candidate_authors author join public.party_members member on member.id=author.party_member_id where author.candidate_id=candidate.id and member.player_id=p_player_id), (select member.color from public.party_members member where member.player_id=p_player_id and member.party_id=party.id),exists(select 1 from public.picture_caption_ballots ballot join public.party_members member on member.id=ballot.party_member_id where ballot.round_id=round.id and member.player_id=p_player_id),session.id,session.revision from public.parties party join public.game_sessions session on session.id=party.current_game_session_id join public.picture_caption_rounds round on round.game_session_id=session.id and round.state='active' and round.phase='voting' join public.picture_caption_candidates candidate on candidate.round_id=round.id where party.code=upper(trim(p_party_code)) and exists(select 1 from public.party_members member join public.picture_caption_round_members eligible on eligible.party_member_id=member.id and eligible.round_id=round.id where member.player_id=p_player_id and member.party_id=party.id) order by candidate.display_position;
$$;
create function public.host_picture_caption_ballots_projection(p_host_id uuid,p_party_id uuid) returns table(candidate_id uuid,caption text,display_position integer,points integer,voter_nickname text,game_session_id uuid,session_revision bigint) language sql stable security definer set search_path='' as $$
 select candidate.id,candidate.caption,candidate.display_position,candidate.points,voter.nickname,session.id,session.revision from public.parties party join public.game_sessions session on session.id=party.current_game_session_id join public.picture_caption_rounds round on round.game_session_id=session.id and round.state='active' and round.phase='voting' join public.picture_caption_candidates candidate on candidate.round_id=round.id left join public.picture_caption_ballots ballot on ballot.candidate_id=candidate.id left join public.party_members voter on voter.id=ballot.party_member_id where party.host_id=p_host_id and party.id=p_party_id order by candidate.display_position;
$$;
create function public.display_picture_caption_candidates_projection(p_display_session_id uuid,p_party_code text) returns table(candidate_id uuid,caption text,display_position integer,game_session_id uuid,session_revision bigint) language sql stable security definer set search_path='' as $$
 select candidate.id,candidate.caption,candidate.display_position,session.id,session.revision from public.display_sessions display_session join public.parties party on party.id=display_session.party_id join public.game_sessions session on session.id=party.current_game_session_id join public.picture_caption_rounds round on round.game_session_id=session.id and round.state='active' and round.phase='voting' join public.picture_caption_candidates candidate on candidate.round_id=round.id where display_session.id=p_display_session_id and display_session.revoked_at is null and party.code=upper(trim(p_party_code)) order by candidate.display_position;
$$;
revoke all on function public.player_picture_caption_candidates_projection(uuid,text),public.host_picture_caption_ballots_projection(uuid,uuid),public.display_picture_caption_candidates_projection(uuid,text) from public,anon,authenticated;
grant execute on function public.player_picture_caption_candidates_projection(uuid,text),public.host_picture_caption_ballots_projection(uuid,uuid),public.display_picture_caption_candidates_projection(uuid,text) to service_role;